import type { Event, Album } from '../types';

export const mockEvents: Event[] = [
  {
    id: '2026-03-14-kichimu',
    title_en: 'Iteza to Otomeza',
    title_ja: '射手座と乙女座',
    date: '2026-03-14',
    venue_en: 'Kichijoji Kichimu',
    venue_ja: '吉祥寺・キチム',
    city_en: 'Kichijoji',
    city_ja: '吉祥寺',
    doors: '16:30',
    start: '17:00',
    adv_price: '¥4,500',
    door_price: '¥5,000 (+1 drink)',
    ticketUrl: 'https://page.kichimu.la/iteza/',
    performers: '高田漣, advantage Lucy (サポルーシー), 山田稔明',
    featured: true,
    body_en: 'An intimate afternoon show at Kichijoji Kichimu. Children under school age admitted free.',
    body_ja: '吉祥寺キチムでのアフタヌーンショー。未就学児無料＝入場無料。',
  },
  {
    id: '2025-12-05-kansai-nominoichi',
    title_en: 'Kansai Flea Market',
    title_ja: '関西蚤の市',
    date: '2025-12-05',
    venue_en: 'Kansai Flea Market Venue',
    venue_ja: '関西蚤の市会場',
    city_en: 'Osaka',
    city_ja: '大阪',
    start: '11:30',
    end_time: '12:10',
    performers: 'advantage Lucy (サポルーシー)',
    ticketUrl: 'https://tokyonominoichi.com/kansai_2025_winter/',
    body_en: 'advantage Lucy performing at the Kansai Flea Market winter edition.',
    body_ja: '関西蚤の市の冬版でadvantage Lucyが出演。',
  },
  {
    id: '2025-11-30-arpeggio-vol21',
    title_en: 'Mune-Kyun ♡ Arpeggio vol.21 — 23rd Anniversary of Fukumura Takayuki',
    title_ja: '胸キュン♡アルペジオ vol.21〜福村貴行くんの23回忌〜',
    date: '2025-11-30',
    venue_en: 'CLUB Que',
    venue_ja: 'CLUB Que',
    city_en: 'Shimokitazawa',
    city_ja: '下北沢',
    doors: '18:00',
    start: '18:30',
    adv_price: '¥3,000',
    door_price: '¥3,300 (+1 drink ¥600)',
    performers: 'advantage Lucy, VASALLO CRAB 75, Moon In June, DJ ぱまら',
    ticketUrl: 'https://forms.gle/QKxmtjFHXRC8ffqD6',
    featured: true,
    body_en: 'The annual tribute concert for founding member Fukumura Takayuki. Also available via PPV streaming (¥2,500).',
    body_ja: '創設メンバー福村貴行の追悼コンサート。PPV配信もあり（¥2,500）。',
  },
];

export const mockAlbums: Album[] = [
  {
    id: 'station',
    title: 'Station',
    year: '2000',
    type: 'album',
    label: 'Toshiba-EMI',
    description_en: 'Second major-label album. A journey through moods and seasons.',
    description_ja: 'メジャーセカンドアルバム。気分と季節を旅する作品。',
  },
  {
    id: 'fanfare',
    title: 'Fanfare',
    year: '1999',
    type: 'album',
    label: 'Toshiba-EMI',
    description_en: 'Major-label debut. Bright, confident indie pop full of hooks.',
    description_ja: 'メジャーデビューアルバム。明るく自信に満ちたインディーポップ。',
  },
  {
    id: 'echo-park',
    title: 'Echo Park',
    year: '2005',
    type: 'album',
    label: 'Solaris Records',
    description_en: 'Their most accomplished album. Sun-soaked melodies with a touch of California dreaming.',
    description_ja: '最も完成度の高いアルバム。太陽に満ちたメロディとカリフォルニアの夢。',
  },
];
